### ISSUE TITLE
Error handling when Jira issue is not found or No permissions

### ISSUE THREAD

**Issue by keshavprasadms** [cakeinpanic/jira-description-action#11]
Error countered. Needs exception handling.
```looking in: fix: chore
looking in: release-3.7.0
JIRA key -> RELEASE-3
{
  error: Error: Request failed with status code 404
      at createError (/home/runner/work/_actions/keshavprasadms/jira-description-action/0.0.2/lib/index.js:1:4651)
      at settle (/home/runner/work/_actions/keshavprasadms/jira-description-action/0.0.2/lib/index.js:1:121051)
      at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/keshavprasadms/jira-description-action/0.0.2/lib/index.js:1:129014)
      at IncomingMessage.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    config: {
      url: '/issue/RELEASE-3?fields=project,summary,issuetype',
      method: 'get',
      headers: [Object],
      baseURL: '***rest/api/3',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 2000,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: ***,
      shouldKeepAlive: ***,
      useChunkedEncodingByDefault: ***,
      sendDate: ***,
      _removedConnection: ***,
      _removedContLen: ***,
      _removedTE: ***,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /rest/api/3/issue/RELEASE-3?fields=project,summary,issuetype HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Basic ***\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: project-sunbird.atlassian.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/rest/api/3/issue/RELEASE-3?fields=project,summary,issuetype',
      _ended: true,
      res: [IncomingMessage],
      aborted: ***,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: ***,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(kNeedDrain)]: ***,
      [Symbol(isCorked)]: ***,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: {
      status: 404,
      statusText: 'Not Found',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function]
  }
}
Error: Request failed with status code 404
```

**Comment by keshavprasadms** [comment]
Fixed - https://github.com/cakeinpanic/jira-description-action/pull/12
